apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: migration-tool-frontend
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: migration-tool
    component: frontend
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/nginx-122:latest
  output:
    to:
      kind: ImageStreamTag
      name: migration-tool-frontend:latest
  triggers:
    - type: ConfigChange
