apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: migration-tool-frontend
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: migration-tool
    component: frontend
spec:
  to:
    kind: Service
    name: migration-tool-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
